In [1]:
import tensorflow as tf

# 1. Create a random tensor of shape (4, 6)
tensor_4_6 = tf.random.uniform(shape=(4, 6))
print("Original tensor:")
print(tensor_4_6)

# 2. Find its rank and shape
rank = tf.rank(tensor_4_6)
shape = tf.shape(tensor_4_6)
print(f"\nRank: {rank}")
print(f"Shape: {shape}")

# 3. Reshape and transpose
# Reshape to (2, 3, 4)
reshaped_tensor = tf.reshape(tensor_4_6, (2, 3, 4))
print("\nReshaped tensor (2, 3, 4):")
print(reshaped_tensor)

# Transpose to (3, 2, 4)
transposed_tensor = tf.transpose(reshaped_tensor, perm=[1, 0, 2])
print("\nTransposed tensor (3, 2, 4):")
print(transposed_tensor)

# Print rank and shape after reshaping/transposing
print(f"\nRank after reshaping: {tf.rank(reshaped_tensor)}")
print(f"Shape after reshaping: {tf.shape(reshaped_tensor)}")
print(f"Rank after transposing: {tf.rank(transposed_tensor)}")
print(f"Shape after transposing: {tf.shape(transposed_tensor)}")

# 4. Broadcasting and addition
# Create a smaller tensor of shape (1, 4)
smaller_tensor = tf.random.uniform(shape=(1, 4))
print("\nSmaller tensor (1, 4):")
print(smaller_tensor)

# Broadcasting and adding
broadcasted_sum = reshaped_tensor + smaller_tensor[:, tf.newaxis, :]
print("\nResult after broadcasting and addition:")
print(broadcasted_sum)

# 5. Explanation of broadcasting in TensorFlow
print("\nExplanation of broadcasting:")
print("Broadcasting in TensorFlow allows arithmetic operations between tensors of different shapes.")
print("The smaller tensor (1, 4) is broadcast to match the shape of the reshaped tensor (2, 3, 4).")
print("1. The smaller tensor is expanded to (1, 1, 4).")
print("2. This is then repeated to match the shape (2, 3, 4).")
print("3. Finally, element-wise addition is performed.")
print("This allows efficient operations between tensors of different shapes without manually replicating data.")


Original tensor:
tf.Tensor(
[[0.17860734 0.9222386  0.49763513 0.27867055 0.7857331  0.8931309 ]
 [0.7142072  0.908712   0.19561684 0.5880488  0.99018705 0.02816105]
 [0.96548665 0.7820189  0.5720879  0.572971   0.7852955  0.880085  ]
 [0.30672884 0.8750787  0.40881324 0.73967266 0.5764996  0.33520496]], shape=(4, 6), dtype=float32)

Rank: 2
Shape: [4 6]

Reshaped tensor (2, 3, 4):
tf.Tensor(
[[[0.17860734 0.9222386  0.49763513 0.27867055]
  [0.7857331  0.8931309  0.7142072  0.908712  ]
  [0.19561684 0.5880488  0.99018705 0.02816105]]

 [[0.96548665 0.7820189  0.5720879  0.572971  ]
  [0.7852955  0.880085   0.30672884 0.8750787 ]
  [0.40881324 0.73967266 0.5764996  0.33520496]]], shape=(2, 3, 4), dtype=float32)

Transposed tensor (3, 2, 4):
tf.Tensor(
[[[0.17860734 0.9222386  0.49763513 0.27867055]
  [0.96548665 0.7820189  0.5720879  0.572971  ]]

 [[0.7857331  0.8931309  0.7142072  0.908712  ]
  [0.7852955  0.880085   0.30672884 0.8750787 ]]

 [[0.19561684 0.5880488  0.99018705 0.0281